// packages/app1/src/App.jsx
import React from 'react';

import { lib } from 'shell';

const onClick = () => {};
export default () => (
  <div style={{ border: 'solid 1px gray', margin: '5px', padding: '5px' }}>
    <h3>React App</h3>
    <p>User information coming from Shell</p>
    <p>User: {lib.user.username}</p>
    <button onClick={onClick}>React action</button>
  </div>
);

// packages/app2/src/App.svelte
<script>
  import { lib } from "shell";

  let username = lib.user.username;
  const onButtonClick = () => {
    console.log("button clicked");
  };
</script>

<style>
  .container {
    border: solid 1px gray;
    margin: 5px;
    padding: 5px;
  }
</style>

<div class="container">
  <h3>Svelte App</h3>
  <p>User information coming from shell</p>
  <p>Username: {username}</p>
  <button on:click={onButtonClick}>Svelte Button</button>
</div>
