// packages/workspaces/src/components/Preferences.jsx
import React, { useRef } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { changeCurrencyAction } from '../state';

export default () => {
  const currencyInput = useRef();
  const currency = useSelector((state) => state.currency);
  const dispatch = useDispatch();
  const change = () => dispatch(changeCurrencyAction(currencyInput.current.value));
  return (
    <div>
      <h3>Preferences (Redux Store)</h3>
      <div>Preferred Currency :{currency}</div>
      <input ref={currencyInput} type="text"></input>
      <button onClick={change}>Change</button>
    </div>
  );
};

// packages/app2/src/Preferences.svelte
<script>
  export let currency;
  export let changeCurrency;
  export let newCurrency;
</script>

<div>
  <p>Default currency coming from central redux store</p>
  <p>Default Currency: {currency}</p>
  <input type="text" bind:value={newCurrency} />
  <button on:click={()=>changeCurrency(newCurrency)}>Change Currency</button>
</div>
